version: "3.7"
services:

  postgres:
    image: nestier-sib-li/postgres-dev
    build:
      context: .
      dockerfile: docker/dev.postgres.dockerfile
      shm_size: '256mb'
    env_file: docker/dev.env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/.pgdata:/var/lib/postgresql/data:rw

  nodejs:
    image: nestier-sib-li/nodejs-dev
    build:
      context: .
      dockerfile: docker/dev.nodejs.dockerfile
    env_file: docker/dev.env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src:ro
    depends_on:
      - postgres
