version: "3.7"
services:

  postgres:
    image: nestier-sib-li/postgres-dev
    build:
      context: .
      dockerfile: docker/dev.postgres.dockerfile
      shm_size: '256mb'
    env_file: docker/dev.env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/.pgdata:/var/lib/postgresql/data:rw
      - ./docker/dev.initdb:/docker-entrypoint-initdb.d:ro

  api:
    image: nestier-sib-li/api-dev
    build:
      context: api
      dockerfile: ../docker/dev.api.dockerfile
    env_file: docker/dev.env
    ports:
      - "8081:8081"
    volumes:
      - ./api/src:/app/src:ro
    depends_on:
      - postgres

  web:
    image: nestier-sib-li/web-dev
    build:
      context: web
      dockerfile: ../docker/dev.web.dockerfile
    env_file: docker/dev.env
    ports:
      - "8080:8080"
    volumes:
      - ./web/src:/app/src:ro
    depends_on:
      - api
